CREATE DATABASE IF NOT EXISTS `schoolsystemdb`;
USE `schoolsystemdb`;

-- 1. 建立學生表 (Students)
CREATE TABLE Students (
    STU_ID VARCHAR(10) PRIMARY KEY,
    STU_NAME VARCHAR(50) NOT NULL,
    CLASS_NAME VARCHAR(20) NOT NULL,
    SEAT_NUM INT
);

-- 2. 建立課程表 (Courses)
CREATE TABLE Courses (
    COURSE_ID VARCHAR(10) PRIMARY KEY,
    COURSE_NAME VARCHAR(100) NOT NULL,
    SEMESTER VARCHAR(20) NOT NULL
);

-- 3. 建立修課表 (Enrollments)
CREATE TABLE Enrollments (
    ENROLL_ID VARCHAR(10) PRIMARY KEY,
    STU_ID VARCHAR(10),
    COURSE_ID VARCHAR(10),
    FOREIGN KEY (STU_ID) REFERENCES Students(STU_ID),
    FOREIGN KEY (COURSE_ID) REFERENCES Courses(COURSE_ID)
);

-- 4. 建立評量項目表 (Assessments)
CREATE TABLE Assessments (
    AST_ID VARCHAR(10) PRIMARY KEY,
    COURSE_ID VARCHAR(10),
    AST_NAME VARCHAR(100) NOT NULL,
    CATEGORY VARCHAR(50),
    WEIGHT INT,
    FOREIGN KEY (COURSE_ID) REFERENCES Courses(COURSE_ID)
);

-- 5. 建立成績表 (Scores)
CREATE TABLE Scores (
    SCORE_ID VARCHAR(10) PRIMARY KEY,
    STU_ID VARCHAR(10),
    AST_ID VARCHAR(10),
    SCORE INT,
    FOREIGN KEY (STU_ID) REFERENCES Students(STU_ID),
    FOREIGN KEY (AST_ID) REFERENCES Assessments(AST_ID)
);

-- 6. 建立學生作品表 (Portfolios)
CREATE TABLE Portfolios (
    PORTFO_ID VARCHAR(10) PRIMARY KEY,
    STU_ID VARCHAR(10),
    COURSE_ID VARCHAR(10),
    AST_ID VARCHAR(10),
    TITLE VARCHAR(200),
    UPLOAD_DATE DATE,
    FILE_URL VARCHAR(500),
    FOREIGN KEY (STU_ID) REFERENCES Students(STU_ID),
    FOREIGN KEY (COURSE_ID) REFERENCES Courses(COURSE_ID),
    FOREIGN KEY (AST_ID) REFERENCES Assessments(AST_ID)
);
